name: forced_update
description: Flutter plugin for forcing users to update the installed app. Forced update can be based on Major, Minor or Patch version updates. 
version: 0.1.0+1
author: Paddo <flutter@paddo.org>
homepage: https://github.com/paddo/forced_update/tree/master/forced_update

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.0.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
